---
name: {%= name %}
title: {%= title %}
group: {%= group %}
company: com
description: webapp {%= group %} {%= name %}
isRoot: true
framework:
  name: stuff
  version: 7.10.0
  builder: rollup
  skipCommandTerser: true
  useCodeSplitting: true
  custom: 0
template:
  format: html
  debug:
    appInLibMap: true
    format: es
    src: template/debug.es.html
    dest: index.html
  release:
    appInLibMap: true
    format: es
    src: template/release.es.html
    dest: index.html
version: 1.0.0
author:
  name: astro
  email: www@astrocorp.com.tw
  url: www.astrocorp.com.tw
licenses:
  -
    type: MIT
    url: undefined/blob/master/LICENSE-MIT
keywords:
  - HTML5
  - game
  - es6
  - app
#excluded:
#  autoTest: true

