name: 測試
on:
  push:
    branches: [beta, upload]
jobs:
  release:
    env:
      STUFF_DEBUG: 1
      STUFF_MODE: release
      STUFF_UPLOAD: beta
    runs-on: [self-hosted, x64, game]
    name: 營運版
    steps:
      - name: 訊息
        run: |
          . stuff-env
          report "複製專案"
      - uses: actions/checkout@v3
      - name: 部署
        run: stuff deploy
