---
name: {%= name %}
title: {%= title %}
group: {%= group %}
company: com
description: webapp {%= group %} {%= name %}
version: 1.0.0
generatorVendor: v2
framework:
  name: stuff
  version: 6.2.0
  builder: rollup
  skipCommandTerser: true
  useCodeSplitting: true
author:
  name: astro
  email: www@astrocorp.com.tw
  url: www.astrocorp.com.tw
licenses:
  -
    type: MIT
    url: undefined/blob/master/LICENSE-MIT
keywords:
  - HTML5
  - game
  - es6
  - app
excluded:
  autoTest: true

