name: 檢查
on: 
  push:
    branches: '**'
jobs:
  check-code-style:
    env:
      STUFF_DEBUG: 1
    runs-on: [self-hosted, x64, game]
    name: 檢查程式碼
    steps:
      - name: 訊息
        run: |
          . stuff-env
          report "複製專案"
      - uses: actions/checkout@v3
      - name: eslint
        run: stuff eslint
