env:
  browser: true
  node: true
  worker: true
  es2021: true
extends: 
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser' # babel-eslint
plugins: 
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: 2021
  allowImportExportEverywhere: true
  codeFrame: false
  sourceType: module
globals:
  ALPHA: true
  BETA: true
  DEMO: true
  TEST: true
  DEBUG: true
  console: true
  PIXI: true
  System: true
  createjs: true
  isMobile: true
rules:
  space-before-function-paren:
    - 2
    - always
  indent:
    - 2
    - 2
    - SwitchCase: 1
  no-console:
    - 2
    - allow:
      - log
      - warn
      - error
      - info

  no-empty:
    - 2
    - allowEmptyCatch: true
  no-spaced-func: 2
  array-bracket-spacing:
    - 2
    - always
  space-in-parens:
    - 2
    - never
  quote-props:
    - 2
    - as-needed
  key-spacing:
    - 2
    - beforeColon: false
      afterColon: true
  space-unary-ops:
    - 2
    - words: false
      nonwords: false
  no-mixed-spaces-and-tabs: 2
  no-trailing-spaces: 2
  comma-spacing:
    - 2
    - after: true
      before: false
  comma-style:
    - 2
    - last
  comma-dangle:
    - 2
    - never
  yoda:
    - 2
    - never
  no-with: 2
  brace-style:
    - 2
    - 1tbs
    - allowSingleLine: true
  no-multiple-empty-lines: 2
  no-multi-str: 2
  one-var: 0
  semi-spacing:
    - 2
    - before: false
      after: true
  space-before-blocks:
    - 2
    - always
  wrap-iife: 2
  space-infix-ops: 2
  camelcase:
    - 2
    - properties: always
  eol-last: 2
  dot-notation: 2
  curly: 2
  keyword-spacing:
    - 2
    - {}
  lines-around-comment:
    - 2
    - beforeLineComment: true
  valid-jsdoc:
    - 0
  semi:
    - 2
    - always
  consistent-this:
    - 2
    - self
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
    - avoidEscape: true
  max-len:
    - 2
    - 120
  strict: 0
  eqeqeq: 2
  no-eq-null: 2
  no-use-before-define:
    - 2
    - functions: false
  no-caller: 2
  no-undef: 2
  no-unused-vars: 2
  no-cond-assign:
    - 2
    - except-parens
  max-params:
    - 2
    - 4
  max-depth:
    - 2
    - 6
