name: 更新
on:
  push:
    branches: [update]
jobs:
  release:
    env:
      STUFF_DEBUG: 1
    runs-on: [self-hosted, x64, game]
    name: package
    steps:
      - name: 訊息
        run: |
          . stuff-env
          report "複製專案"
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: 部署
        run: |
          mkdir -p /tmp/ramdisk/stuff/
          cp /actions-runner/_work/stuff/stuff/* -Rf /tmp/ramdisk/stuff/
          cd /tmp/ramdisk/stuff/
          npm install

